### ISSUE TITLE
Use built-in md5 method

### ISSUE THREAD

**Issue by pditommaso** [gis-rpd/rpd-sg10k-grch38-gatk4-gvcf-freebayes-vcf#41]
Groovy provides an handy built-in [md5](http://docs.groovy-lang.org/next/html/groovy-jdk/java/lang/CharSequence.html#md5()) method. 

Therefore [this snippet](https://github.com/gis-rpd/rpd-sg10k-grch38-gatk4-gvcf-freebayes-vcf/blob/master/main.nf#L19-L22) can be replaced with just `str.md5()` eg. 

```
import java.security.MessageDigest
def generateMD5_A(String s){
    MessageDigest.getInstance("MD5").digest(s.bytes).encodeHex().toString()
}

assert generateMD5_A('abc')=='abc'.md5()
```

**Comment by andreas-wilm** [comment]
Thanks! Good to know. Turns out it was orphaned anyway
